#!/bin/bash

#   Copyright 2026 Brianna Bennett
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Note: bash is used because it's almost always available, zsh might not be.

cd "$(dirname "$0")"
shopt -s extglob

dotfiles_base=$(git rev-parse --show-toplevel)

for sourcefile in !(README.md|setup)
do
  dotfile=~/.${sourcefile}
  sourcefile=${dotfiles_base}/${sourcefile} # I'm not sure I like this much
  if [ -L "${dotfile}" ] || ! [ -f "${dotfile}" ]
  then
    rm -f "${dotfile}"
    ln -s "${sourcefile}" "${dotfile}"
  else
    echo "${dotfile} exists, I will not clobber it."
  fi
done

function set_git_opt() {
    option="$1"
    value="$2"

    git config "$option" || git config --global "$option" "$value"
}

# Set up git options
{
    set_git_opt core.excludesfile "$HOME/.gitignore.global"
    set_git_opt include.path "${dotfiles_base}/gitconfig.roaming"

    # Better tag handling
    set_git_opt fetch.pruneTags true
    set_git_opt pull.pruneTags true
    set_git_opt remote.origin.tagOpt --true

    # Make git branch behavior work correctly.
    set_git_opt branch.autoSetupMerge always
    set_git_opt checkout.defaultRemote origin
    set_git_opt pull.default current
    set_git_opt pull.rebase true
    set_git_opt push.default current
    set_git_opt push.autoSetupRemote true
    set_git_opt remote.pushDefault origin

    set_git_opt github.user bahamat
} >/dev/null

# Set up npm options
# See https://docs.npmjs.com/getting-started/fixing-npm-permissions
{
    npm config set progress false
    npm config set depth 0
    npm config set unsafe-perm true
}

git submodule init >/dev/null
git submodule update --depth=1 >/dev/null
git submodule foreach 'git reset HEAD --hard' >/dev/null
