#!/bin/bash

#   Copyright 2012 Brian Bennett
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Note: bash is used because it's almost always available, zsh might not be.

cd "$(dirname "$0")"
shopt -s extglob

dotfiles_base=$(git rev-parse --show-toplevel)

for sourcefile in !(README.md|setup)
do
  dotfile=~/.${sourcefile}
  sourcefile=${dotfiles_base}/${sourcefile} # I'm not sure I like this much
  if [ -L "${dotfile}" ] || ! [ -f "${dotfile}" ]
  then
    rm -f "${dotfile}"
    ln -s "${sourcefile}" "${dotfile}"
  else
    echo "${dotfile} exists, I will not clobber it."
  fi
done

# Set up git options
{
    git config core.excludesfile || git config --global core.excludesfile "$HOME/.gitignore.global"
    git config include.path || git config --global include.path "${dotfiles_base}/gitconfig.roaming"
    git config push.default || git config --global push.default "current"
    git config github.user || git config --global github.user "bahamat"
} >/dev/null

# Set up npm options
# See https://docs.npmjs.com/getting-started/fixing-npm-permissions
{
    npm config set progress false
    npm config set depth 0
    npm config set unsafe-perm true
}

git submodule init >/dev/null
git submodule update --depth=1 >/dev/null
git submodule foreach 'git reset HEAD --hard' >/dev/null
